# Generated by Django 4.2.2 on 2023-06-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_auto_20230622_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecanico', models.IntegerField(choices=[[0, 'PEDRO SOTO - Especialista en Electronica automotriz'], [1, 'JORGE GONZALEZ - Especialista en Caja de Cambios'], [2, 'JOSE MUÑOZ - Especialista en Suspención y Dirección']])),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.IntegerField()),
                ('id_vehiculo', models.CharField(max_length=18)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('email_cliente', models.EmailField(max_length=50)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
