# Generated by Django 3.2.19 on 2023-06-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_auto_20230623_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='Detalle',
            new_name='detalle',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='Fecha_Reserva',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='Telefono',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='Rut',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='user',
        ),
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='rut',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_atencion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
