# Generated by Django 3.2.19 on 2023-06-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_auto_20230624_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='detalle',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
