# Generated by Django 3.2.19 on 2023-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0010_alter_trabajo_fecha_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_atencion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
